---
- import_tasks: install.yml
- include_tasks: certificates.yml
  with_items: "{{ proxy_domains | mandatory }}"
  loop_control:
    loop_var: target
  tags:
    - reverse_proxy_certificates
- import_tasks: dhparam.yml
  when: reverse_proxy_use_dhparam
- import_tasks: nginx.yml
