---
- name: Copy basic nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx

- name: Make sure nginx is enabled and running
  systemd:
    name: nginx.service
    enabled: yes
    state: started

- name: Allow www-data to access shadow for PAM
  user:
    append: yes
    groups: shadow
    name: www-data

- name: Create reverse proxy entries
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/reverse_proxy.conf
  notify: Reload nginx