---
- name: Install nginx
  apt:
    name: nginx-full
    state: latest
  when: ansible_pkg_mgr == "apt"

- name: Copy basic nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx

- name: Make sure nginx is enabled and running
  systemd:
    name: nginx.service
    enabled: yes
    state: started

- name: Allow www-data to access shadow for PAM
  user:
    append: yes
    groups: shadow
    name: www-data
